---
name: cds102labs
channels:
  - defaults
  - conda-forge
dependencies:
  - anaconda=custom=py36hbbc8b67_0
  - gxx_linux-64=7.2.0=he93fcd3_8
  - pandoc=2.2.1=0
  - rstudio=1.1.423=hcfd39f1_0
  - pelican
  - markdown
  - typogrify
  - rpy2
  - r-base
  - r-commonmark
  - r-devtools
  - r-essentials
  - r-git2r
  - r-lintr
  - r-nycflights13
  - r-tidyverse
